name: master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Functions to Google Cloud Platform
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo 'hello'
    