name: master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Trigger Functions to Google Cloud Platform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.2
          architecture: x64

      - name: Run Python Linter
        run: |
          pip install flake8
          flake8 --filename=./functions/*py --max-line-length=119

      - name: Autheticate for Google Cloud Platform Access
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy Trigger Functions
        run: |
          pushd .
          cd functions/event-data-stream && gcloud functions deploy send_data_to_firestore --trigger-topic event-data-stream --runtime python37
          popd
          pushd .
          cd functions/threshold && gcloud functions deploy send_sms_message --trigger-topic threshold --runtime python37
          popd
          cd functions/storage && gcloud functions deploy send_climate_data_file_to_storage --trigger-topic storage --runtime python37
    